name: Storefront 1000032769
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      # Install Playwright and Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build and Publish to Oxygen
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000032769 }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: npx shopify hydrogen deploy --auth-bypass-token --token $SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN

      - name: Start Dev Server
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: |
          # Start dev server in background
          SESSION_SECRET=$SESSION_SECRET nohup npm run dev >/dev/null 2>&1 &

          # Wait a few seconds for server to come up
          sleep 15

      - name: Run End-to-end Tests
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: |
          # The server is now presumably listening on http://localhost:3000
          # Make sure your baseURL in playwright config is "http://localhost:3000"
          export AUTH_BYPASS_TOKEN=$(jq -r '.authBypassToken' h2_deploy_log.json)
          export DEPLOYMENT_URL=$(jq -r '.url' h2_deploy_log.json)
          npm run test:e2e

      - name: Upload test screenshots
        if: always() # run this step even if previous step failed
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: debug.png
